# Copyright 2019-2022 Hitachi, Ltd., Hitachi America, Ltd. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

FROM node:14

ARG FABRIC_VERSION

ADD opssc-agent/src /opt/app/src
ADD common /opt/common
# Allow npm to run prepare script as root
RUN cd /opt/common/src; npm --unsafe-perm install
RUN cd /opt/app/src; npm --unsafe-perm install

# Add fabric binaries
RUN cd /
RUN wget https://github.com/hyperledger/fabric/releases/download/v${FABRIC_VERSION}/hyperledger-fabric-linux-amd64-${FABRIC_VERSION}.tar.gz
RUN tar -xzf hyperledger-fabric-linux-amd64-${FABRIC_VERSION}.tar.gz

# Add fabric-configtx-cli
ADD configtx-cli/bin/fabric-configtx-cli /usr/local/bin

# Add helm
ENV HELM_VERSION=v3.10.0
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
RUN chmod 700 get_helm.sh
RUN ./get_helm.sh --version $HELM_VERSION
RUN rm get_helm.sh

# Add kubectl
RUN curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Add chart for chaincode server
COPY opssc-agent/charts/chaincode-server /opt/chart

# Add chaincode for opssc
ADD chaincode /opt/go/src/bootstrap/

# Set default GOPATH
ENV GOPATH=/opt/go

ENTRYPOINT cd /opt/app/src; npm start
