apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opssc-api-server.fullname" . }}
  labels:
    {{- include "opssc-api-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opssc-api-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opssc-api-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opssc-api-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: admin-msp
          configMap:
            name: {{ .Values.secrets.adminMSPName }}
        - name: fabric-ccp
          configMap:
            name: {{ .Values.secrets.connectionProfileName }}
            items:
            - key: {{ .Values.secrets.connectionProfileItemKeyName }}
              path: connection-profile.yaml
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ADMIN_MSPID
              value: {{ .Values.adminMSPID | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: DISCOVER_AS_LOCALHOST
              value: {{ .Values.discoverAsLocalhost | quote }}
            - name: CLIENT_SERVICE_PORT
              value: {{ .Values.service.port | quote }}
            - name: WS_ENABLED
              value: {{ .Values.websocket.enabled | quote }}
            - name: API_CH_PROPOSAL_ENABLED
              value: {{ .Values.api.channelProposalEnabled | quote }}
            - name: API_UTIL_ENABLED
              value: {{ .Values.api.utilEnabled | quote }}
            - name: CHANNEL_NAME
              value: {{ .Values.opsscChannelName | quote }}
            - name: CH_OPS_CC_NAME
              value: {{ .Values.opsscChannelOpsCCName | quote }}
            - name: CC_OPS_CC_NAME
              value: {{ .Values.opsscChaincodeOpsCCName | quote }}
          volumeMounts:
            - mountPath: /tmp/admin-msp.tar
              name: admin-msp
              subPath: admin-msp.tar
            - mountPath: /opt/fabric/config
              name: fabric-ccp
          command: [ "/bin/sh","-c", "tar -xf /tmp/admin-msp.tar -C /opt/fabric && cd /opt/app/src && npm start" ]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
