apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "opssc-agent.serviceAccountName" . }}
  labels:
    {{- include "opssc-agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ''
    - 'apps'
    - 'batch'
    resources:
    - services
    - endpoints
    - deployments
    - replicasets
    - pods
    - secrets
    - configmaps
    - jobs
    verbs:
    - get
    - watch
    - list
    - create
    - update
    - patch
    - delete