apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "opssc-agent.serviceAccountName" . }}
  labels:
    {{- include "opssc-agent.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name:  {{ include "opssc-agent.serviceAccountName" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "opssc-agent.serviceAccountName" . }}
