# Copyright 2019-2021 Hitachi, Ltd., Hitachi America, Ltd. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  test:
    external:
      name: fabric_test

services:
  opssc-api-server.org4.example.com:
    container_name: opssc-api-server.org4.example.com
    image: fabric-opssc/opssc-api-server:${IMAGE_TAG:-latest}
    environment:
      - ADMIN_MSPID=Org4MSP
      - LOG_LEVEL=info
      - DISCOVER_AS_LOCALHOST=false
      - CLIENT_SERVICE_PORT=5003
      - API_CH_PROPOSAL_ENABLED=true
      - API_UTIL_ENABLED=true
    volumes:
      - ../organizations/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp:/opt/fabric/msp
      - ../organizations/peerOrganizations/org4.example.com/connection-org4.yaml:/opt/fabric/config/connection-profile.yaml
    networks:
      - test
    ports:
      - 5003:5003
